name: 'Terraform recursive plan'
description: 'Perform recursive terraform plan and report results'
inputs:
  start_dir:
    description: 'Script root dir'
    required: true
    default: '.'
  environment:
    description: 'Infra environemnt'
    required: true
  batch_size:
    description: 'Number of concurrent terraform processes'
    required: true
    default: 7
runs:
  using: 'node16'
  main: 'dist/index.js'
